export const REQUEST_LOCATION = 'REQUEST_LOCATION';
export const RECEIVE_LOCATION = 'RECEIVE_LOCATION';
export const INVALIDATE_DEFAULT_LOCATION = 'INVALIDATE_DEFAULT_LOCATION';

export const REQUEST_GROUPS = 'REQUEST_GROUPS';
export const RECEIVE_GROUPS = 'RECEIVE_GROUPS';
export const SELECT_GROUP = 'SELECT_GROUP';
export const INVALIDATE_GROUPS = 'INVALIDATE_GROUPS';

export const IGNORE_CHANGE = 'IGNORE_CHANGE';
