export const CHANGE_VOLUME = 'CHANGE_VOLUME';
export const REQUEST_LOCATION = 'REQUEST_LOCATION';
export const RECEIVE_LOCATION = 'RECEIVE_LOCATION';

export const REQUEST_GROUPS = 'REQUEST_GROUPS';
export const RECEIVE_GROUPS = 'RECEIVE_GROUPS';
export const SELECT_GROUP = 'SELECT_GROUP';
export const INVALIDATE_GROUP = 'INVALIDATE_GROUP';
